# Reference: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
version: '3'
services:
  opensearch-node1:
    build: ./elasticsearch
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - plugins.security.audit.type=debug
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the openearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - opensearch-net
  opensearch-node2:
    build: ./elasticsearch
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - plugins.security.audit.type=debug
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  # kibana:
  #   build: ./kibana
  #   container_name: opensearch-kibana
  #   ports:
  #     - 5601:5601
  #   expose:
  #     - "5601"
  #   environment:
  #     ELASTICSEARCH_URL: https://opensearch-node1:9200
  #     ELASTICSEARCH_HOSTS: https://opensearch-node1:9200
  #     elasticsearch.requestHeadersWhitelist: "securitytenant,Authorization,x-forwarded-for,x-proxy-user,x-proxy-roles,x-proxy-ext-spaceids,x-proxy-ext-orgids"
  #     opendistro.security.auth_type: "proxy"
  #     opendistro.security.proxycache.user_header: "x-proxy-user"
  #     opendistro.security.proxycache.roles_header: "x-proxy-roles"

  #   networks:
  #     - opensearch-net
  #   volumes: []

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
